/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.TaoLopController;
import Control.executeSQL;
import CustomTable.CustomTableLop;
import CustomTable.CustomTableSinhVien;
import Model.Lop;
import Model.SinhVien;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author 2XHQ
 */
public class QuanLyLopForm extends javax.swing.JFrame {

    private String filename;
    private TaoLopController taolop = new TaoLopController();
    private executeSQL exsql = new executeSQL();
    public static SinhVien SvSua = new SinhVien();
    public static String tl;
    private ArrayList<SinhVien> dssv;
    private ArrayList<Lop> dslop;

    /**
     * Creates new form QuanLyLop
     */
    public QuanLyLopForm() {
        initComponents();
        setLocationRelativeTo(null);
        PanelTable.setVisible(false);
        dslop = exsql.selectDSLop();
        tableLop.setModel(new CustomTableLop(dslop));
        for (Lop i : dslop) {
            cbbLop.addItem(i.getTenLop().toString());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneltab1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnXoaLop = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableLop = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnOpenfile = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnTaoLop = new javax.swing.JButton();
        cbbNhom = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtfilename = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbbLop = new javax.swing.JComboBox<>();
        btnChonLop = new javax.swing.JButton();
        PanelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSinhVien = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSapXepSTT = new javax.swing.JButton();
        btnSapXepTen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User-Group-icon.png"))); // NOI18N
        jLabel1.setText("Quản lý lớp");

        btnXoaLop.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button-Close-icon.png"))); // NOI18N
        btnXoaLop.setText("Xóa lớp");
        btnXoaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLopActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Go-back-icon.png"))); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tableLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableLop);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoaLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jLabel1)
                .addContainerGap(327, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnXoaLop)
                        .addGap(50, 50, 50)
                        .addComponent(btnBack))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneltab1.addTab("Quản lý lớp", jPanel1);

        btnOpenfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/open-file-icon.png"))); // NOI18N
        btnOpenfile.setText("Open file");
        btnOpenfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenfileActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button-Close-icon.png"))); // NOI18N
        jButton6.setText("Hủy");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnTaoLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/create-icon.png"))); // NOI18N
        btnTaoLop.setText("Tạo lớp");
        btnTaoLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoLopActionPerformed(evt);
            }
        });

        cbbNhom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbbNhom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngẫu nhiên", "Số thứ tự" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Đường dẫn");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cách tạo nhóm");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Tạo lớp");

        txtfilename.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtfilename.setAutoscrolls(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbNhom, 0, 231, Short.MAX_VALUE)
                    .addComponent(txtfilename))
                .addGap(37, 37, 37)
                .addComponent(btnOpenfile)
                .addGap(42, 42, 42)
                .addComponent(jButton6)
                .addGap(114, 114, 114))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(btnTaoLop))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addGap(91, 91, 91)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpenfile)
                    .addComponent(jButton6)
                    .addComponent(jLabel2)
                    .addComponent(txtfilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbNhom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(39, 39, 39)
                .addComponent(btnTaoLop)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        paneltab1.addTab("Tạo lớp", jPanel2);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Quản lý sinh viên");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Chọn lớp: ");

        btnChonLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ok-icon.png"))); // NOI18N
        btnChonLop.setText("OK");
        btnChonLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonLopActionPerformed(evt);
            }
        });

        tableSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSinhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSinhVien);

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add-SV-icon_1.png"))); // NOI18N
        btnThem.setText("Thêm sinh viên");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit-Document-icon.png"))); // NOI18N
        btnSua.setText("Sửa thông tin sinh viên");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button-Delete-icon.png"))); // NOI18N
        btnXoa.setText("Xóa sinh viên");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSapXepSTT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sort-columns-icon.png"))); // NOI18N
        btnSapXepSTT.setText("Sắp xếp sinh viên theo nhóm");
        btnSapXepSTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepSTTActionPerformed(evt);
            }
        });

        btnSapXepTen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sort-columns-icon.png"))); // NOI18N
        btnSapXepTen.setText("Sắp xếp theo tên sinh viên");
        btnSapXepTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepTenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTableLayout = new javax.swing.GroupLayout(PanelTable);
        PanelTable.setLayout(PanelTableLayout);
        PanelTableLayout.setHorizontalGroup(
            PanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSapXepSTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSapXepTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        PanelTableLayout.setVerticalGroup(
            PanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanelTableLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnThem)
                .addGap(30, 30, 30)
                .addComponent(btnSua)
                .addGap(32, 32, 32)
                .addComponent(btnXoa)
                .addGap(18, 18, 18)
                .addComponent(btnSapXepSTT)
                .addGap(48, 48, 48)
                .addComponent(btnSapXepTen)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cbbLop, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnChonLop)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(PanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbbLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChonLop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneltab1.addTab("Quản lý sinh viên", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneltab1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneltab1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenfileActionPerformed

        FileNameExtensionFilter ExcelFiller = new FileNameExtensionFilter("Excel", "xls", "xlsx");
        filechooser.setFileFilter(ExcelFiller);
        filechooser.setMultiSelectionEnabled(false);
        int x = filechooser.showDialog(this, "Chon file");
        if (x == JFileChooser.APPROVE_OPTION) {
            txtfilename.setText(filechooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnOpenfileActionPerformed

    private void btnSapXepTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepTenActionPerformed
        // TODO add your handling code here:
        Collections.sort(dssv, new Comparator<SinhVien>() {
            @Override
            public int compare(SinhVien t, SinhVien t1) {
                return t.getTenSV().compareToIgnoreCase(t1.getTenSV());
            }

        }
        );
        tableSinhVien.setModel(new CustomTableSinhVien((dssv)));
    }//GEN-LAST:event_btnSapXepTenActionPerformed

    private void btnChonLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonLopActionPerformed
        // TODO add your handling code here:
        tl = cbbLop.getSelectedItem().toString();
        try {
            dssv = exsql.getSvLopChoose(tl);
            HashSet<SinhVien> set = new HashSet<>(dssv);
            dssv = new ArrayList<>(set);
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyLopForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        tableSinhVien.setModel(new CustomTableSinhVien((dssv)));
        PanelTable.setVisible(true);
    }//GEN-LAST:event_btnChonLopActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        txtfilename.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    public void LoadBangLop() {
        exsql.selectDSLop();
        tableLop.setModel(new CustomTableLop(exsql.getDslop()));
        for (Lop i : exsql.getDslop()) {
            cbbLop.addItem(i.getTenLop().toString());
        }

    }

    private void btnTaoLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoLopActionPerformed
        // TODO add your handling code here:
        
        
        try {
            filename = txtfilename.getText();
            taolop.DocDL(filename);
            if (cbbNhom.getSelectedItem() == "Ngẫu nhiên") {
                taolop.TaoNhomRanDom();
            } else {
                taolop.TaoNhomThuong();
            }
            JOptionPane.showMessageDialog(null, "Tạo lớp thành công \n");
        } catch (IOException ex) {
            
            JOptionPane.showMessageDialog(null, "Tạo lớp Thất bại \n");
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(null, "Tạo lớp Thất bại \n");
        }
        new ChonLeaderForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTaoLopActionPerformed
    
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        new ThemSinhVienForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnThemActionPerformed

    private void tableSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSinhVienMouseClicked
        // TODO add your handling code here:
        int k = tableSinhVien.getSelectedRow();
        SvSua = dssv.get(k);
    }//GEN-LAST:event_tableSinhVienMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (tableSinhVien.getSelectedRow() >= 0) {
            new SuaSinhVienForm().setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Chọn sinh viên muốn sửa thông tin trong bảng.\n");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnSapXepSTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepSTTActionPerformed
        // TODO add your handling code here:
        Collections.sort(dssv, new Comparator<SinhVien>() {
            @Override
            public int compare(SinhVien t, SinhVien t1) {
                return Integer.compare(t.getMaNhom(), t1.getMaNhom());
            }
        }
        );
        tableSinhVien.setModel(new CustomTableSinhVien((dssv)));
    }//GEN-LAST:event_btnSapXepSTTActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (tableSinhVien.getSelectedRow() >= 0) {
            SinhVien e = dssv.get(tableSinhVien.getSelectedRow());
            int k = JOptionPane.showConfirmDialog(null, "Bạn có thực sự muốn xóa sinh viên này không !!!", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (k == JOptionPane.YES_OPTION) {
                try {
                    exsql.deleteSV(e.getMaSV());
                } catch (Exception ex) {
                    Logger.getLogger(QuanLyLopForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                dssv.remove(tableSinhVien.getSelectedRow());
                tableSinhVien.setModel(new CustomTableSinhVien(dssv));
                dslop = exsql.selectDSLop();
                tableLop.setModel(new CustomTableLop(dslop));
                JOptionPane.showMessageDialog(null, "Xóa sinh viên thành công \n");
            } else {
                JOptionPane.showMessageDialog(null, "Chọn sinh viên muốn xóa \n");
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnXoaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLopActionPerformed
        // TODO add your handling code here:
        if (tableLop.getSelectedRow() >= 0) {
            Lop l = dslop.get(tableLop.getSelectedRow());
            try {
                exsql.deleteLop(l.getMaLop());
            } catch (Exception ex) {
                Logger.getLogger(QuanLyLopForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            dslop.remove(tableLop.getSelectedRow());
            tableLop.setModel(new CustomTableLop(dslop));
        } else {
            JOptionPane.showMessageDialog(null, "Bạn phải chọn lớp cần xóa trong bảng \n");
        }
    }//GEN-LAST:event_btnXoaLopActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new DangNhapGiaoVienForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed
    JFileChooser filechooser = new JFileChooser();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyLopForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyLopForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyLopForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyLopForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyLopForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChonLop;
    private javax.swing.JButton btnOpenfile;
    private javax.swing.JButton btnSapXepSTT;
    private javax.swing.JButton btnSapXepTen;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTaoLop;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaLop;
    private javax.swing.JComboBox<String> cbbLop;
    private javax.swing.JComboBox<String> cbbNhom;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane paneltab1;
    private javax.swing.JTable tableLop;
    private javax.swing.JTable tableSinhVien;
    private javax.swing.JTextField txtfilename;
    // End of variables declaration//GEN-END:variables
}
